const QUOTES = [
  { text: "You must be the change you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "Arise, awake, and stop not till the goal is reached.", author: "Swami Vivekananda" },
  { text: "Do not wait for leaders; do it alone, person to person.", author: "Mother Teresa" },
  { text: "Faith is the bird that feels the light when the dawn is still dark.", author: "Rabindranath Tagore" },
  { text: "Take up one idea. Make that one idea your life — think of it, dream of it, live on that idea.", author: "Swami Vivekananda" },
  { text: "The future depends on what you do today.", author: "Mahatma Gandhi" },
  { text: "Where the mind is without fear and the head is held high, into that heaven of freedom, let my country awake.", author: "Rabindranath Tagore" },
  { text: "Dream is not that which you see while sleeping; it is something that does not let you sleep.", author: "Dr. A.P.J. Abdul Kalam" },
  { text: "If you want to shine like a sun, first burn like a sun.", author: "Dr. A.P.J. Abdul Kalam" },
  { text: "Don't take rest after your first victory, because if you fail in second, more lips are waiting to say that your first victory was just luck.", author: "Dr. A.P.J. Abdul Kalam" },
  { text: "Small aim is a crime; have great aim.", author: "Dr. A.P.J. Abdul Kalam" },
  { text: "In a gentle way, you can shake the world.", author: "Mahatma Gandhi" },
  { text: "Strength does not come from physical capacity. It comes from an indomitable will.", author: "Mahatma Gandhi" },
  { text: "All power is within you; you can do anything and everything.", author: "Swami Vivekananda" },
  { text: "Be a hero. Always say, I have no fear.", author: "Swami Vivekananda" },
  { text: "Let me light my lamp, says the star, and never debate if it will dispel the darkness.", author: "Rabindranath Tagore" },
  { text: "The highest education is that which does not merely give us information but makes our life in harmony with all existence.", author: "Rabindranath Tagore" },
  { text: "Man needs his difficulties because they are necessary to enjoy success.", author: "Dr. A.P.J. Abdul Kalam" },
  { text: "You have to grow from the inside out. None can teach you, none can make you spiritual. There is no other teacher but your own soul.", author: "Swami Vivekananda" },
  { text: "Happiness is when what you think, what you say, and what you do are in harmony.", author: "Mahatma Gandhi" },
  { text: "I slept and dreamt that life was joy. I awoke and saw that life was service. I acted and behold, service was joy.", author: "Rabindranath Tagore" },
  { text: "Learning gives creativity, creativity leads to thinking, thinking provides knowledge, knowledge makes you great.", author: "Dr. A.P.J. Abdul Kalam" },
  { text: "Failure will never overtake me if my determination to succeed is strong enough.", author: "Dr. A.P.J. Abdul Kalam" },
  { text: "The best way to find yourself is to lose yourself in the service of others.", author: "Mahatma Gandhi" },
  { text: "Talk to yourself once in a day, otherwise you may miss meeting an excellent person in this world.", author: "Swami Vivekananda" },
  { text: "If you judge people, you have no time to love them.", author: "Mother Teresa" },
  { text: "Not all of us can do great things. But we can do small things with great love.", author: "Mother Teresa" },
  { text: "Peace begins with a smile.", author: "Mother Teresa" },
  { text: "We know what we are, but know not what we may be.", author: "William Shakespeare" },
  { text: "It always seems impossible until it's done.", author: "Nelson Mandela" },
  { text: "Education is the most powerful weapon which you can use to change the world.", author: "Nelson Mandela" },
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { text: "Stay hungry, stay foolish.", author: "Steve Jobs" },
  { text: "Innovation distinguishes between a leader and a follower.", author: "Steve Jobs" },
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { text: "Cowards die many times before their deaths; the valiant never taste of death but once.", author: "Julius Caesar" },
  { text: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle" },
  { text: "Freedom is not worth having if it does not include the freedom to make mistakes.", author: "Mahatma Gandhi" },
  { text: "First they ignore you, then they laugh at you, then they fight you, then you win.", author: "Mahatma Gandhi" },
  { text: "Be the change that you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "Everything you can imagine is real.", author: "Pablo Picasso" },
  { text: "The purpose of our lives is to be happy.", author: "Dalai Lama" },
  { text: "If you don't build your dream, someone else will hire you to help build theirs.", author: "Dhirubhai Ambani" },
  { text: "Pursue excellence, and success will follow.", author: "Rancho (3 Idiots)" },
  { text: "All is well.", author: "Rancho (3 Idiots)" },
  { text: "Don't be pushed by your problems. Be led by your dreams.", author: "Ralph Waldo Emerson" },
  { text: "What you do today can improve all your tomorrows.", author: "Ralph Marston" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "The mind is everything. What you think, you become.", author: "Buddha" },
  { text: "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.", author: "Buddha" },
];

export function getDailyQuote() {
  const now = new Date();
  const dayOfYear = Math.floor((now - new Date(now.getFullYear(), 0, 0)) / 86400000);
  const index = dayOfYear % QUOTES.length;
  return QUOTES[index];
}
